const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const pool = require('@/src/db');
const { v4: uuidv4 } = require('uuid');
const router = express.Router();

const REFRESH_TOKEN_EXPIRY = 30;  // 30 days

// Cookie configuration constants
const COOKIE_CONFIG = {
  httpOnly: true,
  secure: process.env.NODE_ENV === 'production',
  maxAge: REFRESH_TOKEN_EXPIRY * 24 * 60 * 60 * 1000, // 30 days
  sameSite: 'Strict'
};

// ===== UTILITY FUNCTIONS =====

/**
 * Sets a cookie with the provided name, value and standard security settings
 * @param {Object} res - Express response object
 * @param {String} name - Cookie name
 * @param {String} value - Cookie value
 */
const setCookie = (res, name, value, config) => {
  res.cookie(name, value, config);
};

// Utility: Generate tokens
const generateTokens = (userId, deviceId) => {
  console.log(`Generating tokens for user ID: ${userId}`);
  const accessToken = jwt.sign({ userId }, process.env.JWT_SECRET_KEY, { expiresIn: '1h' });
  const refreshToken = jwt.sign({ userId, deviceId }, process.env.JWT_REFRESH_SECRET_KEY, { expiresIn: REFRESH_TOKEN_EXPIRY * 24 * 60 * 60 }); // 30 days
  return { accessToken, refreshToken };
};

// Utility: Store refresh token in database
const storeRefreshToken = async (userId, deviceId, refreshToken) => {
  try {
    console.log(`Storing refresh token for user ID: ${userId}`);
    await pool.query('DELETE FROM refresh_tokens WHERE user_id = $1', [userId]);

    // The expiration date is already handled for the client with the cookie expiration but storing the expiration for the server is still useful
    const refreshTokenExpiry = new Date();
    refreshTokenExpiry.setDate(refreshTokenExpiry.getDate() + REFRESH_TOKEN_EXPIRY);

    await pool.query(
      'INSERT INTO refresh_tokens (user_id, device_id, token, expires_at) VALUES ($1, $2, $3, $4)',
      [userId, deviceId, refreshToken, refreshTokenExpiry]
    );
  } catch (error) {
    console.error(`Error storing refresh token for user ID: ${userId}`, error);
  }
};

/**
 * Authenticates a user by generating tokens and setting cookies
 * @param {String} userId - User ID
 * @param {Object} res - Express response object
 * @param {String} deviceId - Device ID, generated by the server
 * @returns {Promise<void>}
 */
const authenticateUser = async (userId, res) => {
  const deviceId = uuidv4();

  const { accessToken, refreshToken } = generateTokens(userId, deviceId);
  await storeRefreshToken(userId, deviceId, refreshToken);

  console.log("Setting cookies")

  // Set cookies
  setCookie(res, 'accessToken', accessToken, COOKIE_CONFIG); // accessToken cookie lasts as long as refresh token so that we can actually check if the JWT is expired
  setCookie(res, 'refreshToken', refreshToken, COOKIE_CONFIG);

  console.log("Successfully set cookies")
};

/**
 * User lookup factory function that generates specific user finder methods
 * @param {String} field - Database field to search by
 * @returns {Function} - Function that finds a user by the specified field
 */
const createUserFinder = (field) => {
  return async (value) => {
    const result = await pool.query(`SELECT * FROM users WHERE ${field} = $1`, [value]);
    return result.rows[0];
  };
};

// Delete expired refresh tokens
const deleteExpiredRefreshTokens = async () => {
  console.log('Checking for expired refresh tokens...');

  try {
    // Find expired refresh tokens
    const result = await pool.query(
      'SELECT * FROM refresh_tokens WHERE expires_at < NOW()'
    );

    const expiredTokens = result.rows;
    expiredTokens.forEach(async (token) => {
      await pool.query('DELETE FROM refresh_tokens WHERE id = $1', [token.id]);
      console.log(`Deleted expired refresh token for device ID: ${token.device_id}`);
    });

    console.log('Expired refresh tokens cleanup completed');
  } catch (error) {
    console.error('Error deleting expired refresh tokens:', error);
  }
};

// Delete expired refresh tokens every 24 hours
setInterval(deleteExpiredRefreshTokens, 86400000);

// User finder methods
const findUserById = createUserFinder('id');
const findUserByUsername = createUserFinder('username');
const findUserByEmail = createUserFinder('email');

// ===== MIDDLEWARE =====

// Middleware to verify access token
const verifyAccessToken = async (req, res, next) => {
  console.log(`Verifying access token for protected path: ${req.originalUrl}`);
  const accessToken = req.cookies?.accessToken;

  if (!accessToken) {
    console.log("Missing access token")
    return res.status(401).json({ message: 'Missing access token' });
  }
  
  const decoded = jwt.decode(accessToken); // Decode without verifying

  if (!decoded || !decoded.exp || Date.now() >= decoded.exp * 1000) {
    console.log("Access token expired...");
    return refreshAccessToken(req, res, next);
  }

  try {
    const verified = jwt.verify(accessToken, process.env.JWT_SECRET_KEY);
    req.userId = verified.userId;
    console.log("Access token verified!");
    return next();
  } catch (error) {
    console.error("JWT verification error:", error);
    return res.status(401).json({ message: "Invalid access token" });
  }
};

const refreshAccessToken = async (req, res, next) => {
  console.log("Refreshing user access token");
  const refreshToken = req.cookies.refreshToken;

  if (!refreshToken) {
    console.log('Missing refresh token');
    return res.status(401).json({ message: 'Missing refresh token' });
  }

  try {
    const decoded = jwt.verify(refreshToken, process.env.JWT_REFRESH_SECRET_KEY);

    const result = await pool.query(
      'SELECT * FROM refresh_tokens WHERE user_id = $1 AND device_id = $2 AND token = $3',
      [decoded.userId, decoded.deviceId, refreshToken]
    );

    if (result.rows.length === 0) {
      console.log(`Invalid refresh token for user ID: ${decoded.userId}`);
      return res.status(403).json({ message: 'Invalid refresh token' });
    }

    console.log("Found valid refresh token!")

    console.log(`Generating new tokens for user ID: ${decoded.userId}`);
    await authenticateUser(decoded.userId, res);

    req.userId = decoded.userId;
    return next();
  } catch (error) {
    console.error('Error verifying refresh token:', error);
    return res.status(403).json({ message: 'Invalid or expired refresh token' });
  }
};

// ===== ROUTES =====

// Verify access token
// if access token is invalid but there is a valid refresh token it will refresh the access token
router.get('/verify-token', verifyAccessToken, async (req, res) => {
  // verifyAccessToken will send a response early if verification fails, so we now token is valid at this point
  res.status(200).json({ message: 'Token is valid' });
});

// Register user
router.post('/register', async (req, res) => {
  const { username, email, password } = req.body;

  try {
    console.log(`Registering user: ${username}`);
    const hashedPassword = await bcrypt.hash(password, 10);

    // Insert user into the database
    const result = await pool.query(
      'INSERT INTO users (username, email, password_hash) VALUES ($1, $2, $3) RETURNING *',
      [username, email, hashedPassword]
    );

    const user = result.rows[0];

    console.log(`User created with ID: ${user.id}`);

    res.status(201).json({ message: 'User created' });
  } catch (error) {
    if (error.code === '23505') {  // PostgreSQL duplicate key error code
      return res.status(400).json({ message: 'Username or email already taken' });
    }
  
    console.error('Error registering user:', error);
    res.status(500).json({ message: 'Error creating user' });
  }
});

router.post('/login', async (req, res) => {
  const { username, password } = req.body;

  try {
    console.log(`Login attempt for: ${username}`);

    // Check if the identifier is an email or a username
    const isEmail = /\S+@\S+\.\S+/.test(username);  // Regular expression to check for email format

    // Find user by either email or username
    let user;
    if (isEmail) {
      user = await findUserByEmail(username); // Function to find user by email
    } else {
      user = await findUserByUsername(username); // Function to find user by username
    }

    if (!user) {
      console.log(`Invalid ${isEmail ? 'email' : 'username'}: ${username}`);
      return res.status(401).json({ message: 'Invalid email/username or password' });
    }

    // Check if the password matches
    const isMatch = await bcrypt.compare(password, user.password_hash);
    if (!isMatch) {
      console.log(`Invalid password for ${isEmail ? 'email' : 'username'}: ${username}`);
      return res.status(401).json({ message: 'Invalid email/username or password' });
    }

    console.log(`Login successful for ${isEmail ? 'email' : 'username'}: ${username}`);
    await authenticateUser(user.id, res);

    res.status(200).json({ message: 'Successful log in' })
  } catch (error) {
    console.error('Error logging in user:', error);
    res.status(500).json({ message: 'Error logging in' });
  }
});

module.exports = { authRoutes: router, verifyAccessToken };